### ISSUE TITLE
Can't installed

### ISSUE THREAD

**Issue by essteffan** [jpastoor/jira-worklog-extractor#2]
Hi. When i try to installed i get the following error.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jpastoor/jira-worklog-extractor could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Can you advise?
Thanks!

**Comment by jpastoor** [comment]
Hi,

What command did you run exactly and which PHP version do you have?

Also adding -v to the command gives even more information about the possible problem.

**Comment by essteffan** [comment]
Hi @jpastoor 
Thanks for the reply
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

The error after i added -v flag:

 [InvalidArgumentException]
  Could not find a matching version of package jpastoor/jira-worklog-extractor. Check the packag
  e spelling, your version constraint and that the package is available in a stability which mat
  ches your minimum-stability (stable).


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:717
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:401
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:121
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:842
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:58
 require() at /usr/local/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by essteffan** [comment]
what do you think?

**Comment by essteffan** [comment]
I don't see the package here, https://packagist.org/?q=jpastoor&p=0

Could you check, please?

**Comment by jpastoor** [comment]
Ah that might be it, added it to packagist. Does it work for you now?

**Comment by essteffan** [comment]
Still got some errors:

composer require jpastoor/jira-worklog-extractor dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jpastoor/jira-worklog-extractor dev-master -> satisfiable by jpastoor/jira-worklog-extractor[dev-master].
    - jpastoor/jira-worklog-extractor dev-master requires chobie/jira-api-restclient dev-master@dev -> satisfiable by chobie/jira-api-restclient[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by essteffan** [comment]
I've tried also with composer require jpastoor/jira-worklog-extractor dev-master@dev 

Problem 1
    - Installation request for jpastoor/jira-worklog-extractor dev-master@dev -> satisfiable by jpastoor/jira-worklog-extractor[dev-master].
    - jpastoor/jira-worklog-extractor dev-master requires chobie/jira-api-restclient dev-master@dev -> satisfiable by chobie/jira-api-restclient[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by essteffan** [comment]
Hi @jpastoor any news?

Thanks!

**Comment by david-mohr** [comment]
If you clone the repo, then run the following command from inside the directory, it should install all the necessary dependencies

```
composer install
```
