### ISSUE TITLE
Issue with the versioning on composer setup command

### ISSUE THREAD

**Issue by Brandonsmith23** [jpastoor/jira-worklog-extractor#3]
Steps to recreate:

1) I cloned down the master in terminal (mac OS):  git clone git@github.com:jpastoor/jira-worklog-extractor.git
2) From user root I ran: cd jira-worklog-extractor-master
3) I ran: composer install
4) I ran: composer require jpastoor/jira-worklog-extractor dev-master@dev

Which produced the following error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package jpastoor/jira-worklog-extractor No version set (parsed as 1.0.0) is satisfiable by jpastoor/jira-worklog-extractor[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
> 
> Installation failed, reverting ./composer.json to its original content.

I feel this is an issue with the version in the composer .json but did not see a version listed.

Please let me know if there is any other information I might provide and thank you for creating this app.

**Comment by jpastoor** [comment]
Hi Brandon,

I don't get your step 4. Is that executed in the directory of your own app, or in the directory of the worklog extractor? 

There might be a conflict between this repository and your app (for instance, it uses some symfony 3 libs).

**Comment by Brandonsmith23** [comment]
This was run from the directory of the worklog extractor as outlined in the read me under USAGE:

composer require jpastoor/jira-worklog-extractor dev-master@dev

Copy the config.json.template to config.json and alter the values........

To surmise, I cloned the repo locally, changed directory into it and ran the command above to get the error.  Nothing was altered from the master of the git repo sans the config.jason as to add my own JIRA credentials.

**Comment by jpastoor** [comment]
Ah then there is the issue. The README assumes that you include the worklog extractor in another project, not run it standalone.

I think it will work without the last command, and step 1-3 is enough to install the worklog extractor.
Can you skip the require thing and move on to copy the JSON file and trying out

`php app.php load-project-totals 2016-01-01 2019-03-31`

If that works then we'll update the readme to be more clear in this regard.
