### ISSUE TITLE
Jira api update for author object

### ISSUE THREAD

**Issue by kbytesys** [jpastoor/jira-worklog-extractor#4]
We can't create reports anymore because the jira api changed:

` $author = $entry["author"]["key"];`

`key` is not a valid attribute of the author object. You can use the `accountId` value instead, but you need to refactor che code in order to show a better display name in the output file.

I don't suggest you to use just the "display name" because it could be not unique and because is not useful as input for the `--authors-whitelist` parameter.

**Comment by jpastoor** [comment]
Hi kbytesys,

Thanks for the headsup. Feel free to send in a pull request if you have time to fix this yourselves. If not I will take a look at it in about 2 weeks when I get back from holidays.

Kind regards
